# Setup
title:        dask-image
tagline:      A collection of libraries to use with Dask for image processing
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       dask-image developers
  url:        https://github.com/dask-image

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag

#Others
markdown: kramdown
